# CMake generated Testfile for 
# Source directory: C:/Users/sokol-pc/devtools-course-practice/modules/fraction
# Build directory: C:/Users/sokol-pc/devtools-course-practice/modules/fraction
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Run "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe")
  set_tests_properties(fraction_can_Run PROPERTIES  LABELS "fraction")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Run "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe")
  set_tests_properties(fraction_can_Run PROPERTIES  LABELS "fraction")
else()
  add_test(fraction_can_Run NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Print_Help_Without_Arguments "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe")
  set_tests_properties(fraction_can_Print_Help_Without_Arguments PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "This is a fraction calculator")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Print_Help_Without_Arguments "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe")
  set_tests_properties(fraction_can_Print_Help_Without_Arguments PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "This is a fraction calculator")
else()
  add_test(fraction_can_Print_Help_Without_Arguments NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Check_Number_Of_Arguments "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "2")
  set_tests_properties(fraction_can_Check_Number_Of_Arguments PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "ERROR: Should be 5 arguments.")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Check_Number_Of_Arguments "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "2")
  set_tests_properties(fraction_can_Check_Number_Of_Arguments PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "ERROR: Should be 5 arguments.")
else()
  add_test(fraction_can_Check_Number_Of_Arguments NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Wrong_Number_Format "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "ip" "2" "3" "+")
  set_tests_properties(fraction_can_Detect_Wrong_Number_Format PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Wrong number format!")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Wrong_Number_Format "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "ip" "2" "3" "+")
  set_tests_properties(fraction_can_Detect_Wrong_Number_Format PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Wrong number format!")
else()
  add_test(fraction_can_Detect_Wrong_Number_Format NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Wrong_Operation_Format "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "1" "2" "3" "+trash")
  set_tests_properties(fraction_can_Detect_Wrong_Operation_Format PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Wrong operation format!")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Wrong_Operation_Format "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "1" "1" "2" "3" "+trash")
  set_tests_properties(fraction_can_Detect_Wrong_Operation_Format PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Wrong operation format!")
else()
  add_test(fraction_can_Detect_Wrong_Operation_Format NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Diff_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "-17" "1" "15" "5" "-")
  set_tests_properties(fraction_can_Diff_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nomirator = -20 Denomirator = 1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Diff_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "-17" "1" "15" "5" "-")
  set_tests_properties(fraction_can_Diff_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nomirator = -20 Denomirator = 1")
else()
  add_test(fraction_can_Diff_Complexs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Mult_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "13" "-2" "3" "4" "*")
  set_tests_properties(fraction_can_Mult_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nominator = 39 Denominator = -8")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Mult_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "13" "-2" "3" "4" "*")
  set_tests_properties(fraction_can_Mult_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nominator = 39 Denominator = -8")
else()
  add_test(fraction_can_Mult_Complexs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Divide_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "3" "4" "15" "20" "/")
  set_tests_properties(fraction_can_Divide_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nominator = 1 Denominator = 1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Divide_Complexs "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "3" "4" "15" "20" "/")
  set_tests_properties(fraction_can_Divide_Complexs PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Nominator = 1 Denominator = 1")
else()
  add_test(fraction_can_Divide_Complexs NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fraction_can_Detect_Divide_By_Zero "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "27" "30" "0" "0" "/")
  set_tests_properties(fraction_can_Detect_Divide_By_Zero PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Denominator can`t be zero. Use denominator = 1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fraction_can_Detect_Divide_By_Zero "C:/Users/sokol-pc/devtools-course-practice/bin/fraction.exe" "27" "30" "0" "0" "/")
  set_tests_properties(fraction_can_Detect_Divide_By_Zero PROPERTIES  LABELS "fraction" PASS_REGULAR_EXPRESSION "Denominator can`t be zero. Use denominator = 1")
else()
  add_test(fraction_can_Detect_Divide_By_Zero NOT_AVAILABLE)
endif()
subdirs("src")
subdirs("test")
subdirs("application")
